// <auto-generated />
using System;
using HayvanBarinagi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HayvanBarinagi.Migrations
{
    [DbContext(typeof(DatabaseContex))]
    [Migration("20230806145719_seedUserTable")]
    partial class seedUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HayvanBarinagi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAdd")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameSurname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAdd = new DateTime(2023, 8, 6, 17, 57, 19, 148, DateTimeKind.Local).AddTicks(9013),
                            NameSurname = "Tuğçe",
                            Password = "123",
                            Role = "user",
                            UserName = "tugce"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAdd = new DateTime(2023, 8, 6, 17, 57, 19, 148, DateTimeKind.Local).AddTicks(9025),
                            NameSurname = "2112@sakarya.edu.tr",
                            Password = "saü",
                            Role = "admin",
                            UserName = "2112@sakarya.edu.tr"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAdd = new DateTime(2023, 8, 6, 17, 57, 19, 148, DateTimeKind.Local).AddTicks(9027),
                            NameSurname = "Tuğçe2",
                            Password = "345",
                            Role = "user",
                            UserName = "tugce2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
